import styles from '../styles/Home.module.css'
import Navbar from './components/Navbar.js'
import Head from 'next/head'
import Image from 'next/image';
const about = () => {
    return (
        <>
        <Head>
          <title>About</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
            <div className={styles.centerDiv}>
                <center><h1 className={styles.title}>About Page</h1></center>
                <Image src="/about.jpg" width={500} height={500}></Image>
            </div>
        </>
    )
}

export default about