import data from '../utils/data';
import Head from 'next/head';
import CommentsTemplate from './components/CommentsTemplate';

const commentsCard = () => {
  return (
    <>
      <Head>
        <title>Next-Comment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className='grid grid-cols-1 gap-1 md:grid-cols-3 lg:grid-cols-4'>
        {data.comments.map((comment) => (
          <CommentsTemplate comment={comment} key={comment.id} />
        ))}
      </div>
    </>
  )
}

export default commentsCard