import styles from '../styles/Home.module.css'
import Head from 'next/head'

const home = () => {
    return (
        <>
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
            <h1 className={styles.title}>
                Welcome to <a href="#">Home</a>
            </h1>
        </>
    );
};

export default home;