import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Basics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Home &rarr;</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor deleniti quis commodi corrupti veritatis natus sint alias sequi architecto aut.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>About &rarr;</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi at explicabo modi iste, ipsam qui corrupti quibusdam. Earum, suscipit vel!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Blog &rarr;</h2>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Rem repellat ratione veritatis optio in tempora quidem eligendi mollitia maiores fugiat?
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Contact &rarr;</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis blanditiis libero velit quod asperiores vero aliquam eveniet unde enim. Facere.
            </p>
          </a>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
